version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4.5-cli

    steps:
      - checkout

      - run: sudo apt update
      - run: sudo docker-php-ext-install bcmath
      - run: composer install -n --prefer-dist
      - run: ./vendor/bin/phpunit
      